### PR TITLE
Fix cases of time zone names that include non-uppercase

### PR DESCRIPTION
**Pull request by dmikurube**
`embulk-core`'s old `DateTimeZoneJacksonModule` has had some inconsistent behavior against "all capital" timezone names v.s. non-"all capital" ones.

For example,
* `PDT` is interpreted as `-08:00` (which is wrong, but it worked like this historically)
* `Pdt` and `pdt` are interpreted as `-07:00` (which is correct...)
* `CET` is interpreted as `"CET"` (`ZoneId.of("CET")`)
* `Cet` and `cet` are interpreted as `+01:00`

Even if it's wrong, `ZoneIdModule.withLegacyNames()` intended to emulate `embulk-core`'s old `DateTimeZoneJacksonModule`, but it was not perfect. This pull request is to follow `embulk-core`'s old `DateTimeZoneJacksonModule`.

### CODE REVIEW

**Comment by dmikurube** [comment]
e6a8436fb21abfe064c75b4bbf4de796e41923b0 is adding tests to check with `embulk-core`'s old `DateTimeZoneJacksonModule`, and it fails.

Then, 5e9e89232ca0574113f6ce2acae8037a6bc13c4d is the fix.

**Comment by dmikurube** [comment]
@huylenq This is the last fix for `embulk-util-config:0.2.0`. Can you have a look?

**Review by huylenq — APPROVED** [review]
LGTM, thanks for the work!

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
