### PR TITLE
Check also with Jackson 2.15.4, 2.16.2, and 2.17.0

### PR DESCRIPTION
**Pull request by dmikurube**

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
CI failed in Jackson 2.16.2 and 2.17.0. Please take a look when you get a chance.

**Comment by dmikurube** [comment]
The test has started to fail since Jackson 2.16.0 because of the following changes:

- https://github.com/FasterXML/jackson-core/pull/1053
- https://github.com/FasterXML/jackson-core/pull/1142

These were "fixing" the following issues:

- https://github.com/FasterXML/jackson-core/issues/1050
- https://github.com/FasterXML/jackson-core/issues/1141

**Review by hiroyuki-sato — APPROVED** [review]
LGTM👍

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
